#!/bin/bash
composer install
php bin/console doctrine:schema:drop --force
php bin/console doctrine:schema:create
php bin/console fixtures:load --quiet
php bin/console assets:install
php bin/console cache:clear

npm install
npm run dfb:build:prod

