<?php

namespace AppBundle\Repository;

/**
 * DonneesCommercialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesCommercialesRepository extends \Doctrine\ORM\EntityRepository
{
}
