<?php

namespace AppBundle\Repository;

/**
 * ImportLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
