<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Pharmacien;

/**
 * OfficineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficineRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPharmacien(Pharmacien $pharmacien, $limit = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select("o")
            ->from("AppBundle:Officine", "o")
            ->leftJoin("o.officinePharmaciens", "op")
            ->leftJoin("op.pharmacien", "p")
            ->where("p.nridInterlocuteur = :nridInterlocuteur")
            ->andWhere("op.dateEntree < :dateNow")
            ->andWhere("op.dateSortie > :dateNow")
            ->orderBy("o.nomPharmacie", "ASC")
            ->setMaxResults($limit);

        $qb->setParameter('nridInterlocuteur', $pharmacien->getNridInterlocuteur());
        $qb->setParameter('dateNow', date("Y-m-d H:i:s"));

        return $qb->getQuery()->getResult();
    }

    public function findFirstByPharmacien(Pharmacien $pharmacien)
    {
        $officines = $this->findByPharmacien($pharmacien,'1');
        if(!empty($officines)){
            return $officines[0];
        }
        return null;
    }

}
