<?php

namespace AppBundle\Repository;

/**
 * OfficinePharmacienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficinePharmacienRepository extends \Doctrine\ORM\EntityRepository
{
}
