<?php

namespace AppBundle\Repository;

/**
 * PharmacienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacienRepository extends \Doctrine\ORM\EntityRepository
{
}
