<?php

namespace AppBundle\Repository;

/**
 * RdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdiRepository extends \Doctrine\ORM\EntityRepository
{
}
