<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rdi extends \AppBundle\Entity\Rdi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'extraData', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'dtcreat', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'creatBy', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'entId', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'theme', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'motif', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'report', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'contact', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'codeReturn', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'media', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'origine', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'messageReturn'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'extraData', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'dtcreat', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'creatBy', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'entId', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'theme', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'motif', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'report', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'contact', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'codeReturn', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'media', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'origine', '' . "\0" . 'AppBundle\\Entity\\Rdi' . "\0" . 'messageReturn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rdi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraData', []);

        return parent::getExtraData();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraData($extraData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraData', [$extraData]);

        return parent::setExtraData($extraData);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtcreat($dtcreat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtcreat', [$dtcreat]);

        return parent::setDtcreat($dtcreat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtcreat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtcreat', []);

        return parent::getDtcreat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntId($entId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntId', [$entId]);

        return parent::setEntId($entId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntId', []);

        return parent::getEntId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotif($motif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotif', [$motif]);

        return parent::setMotif($motif);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotif', []);

        return parent::getMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setReport($report)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReport', [$report]);

        return parent::setReport($report);
    }

    /**
     * {@inheritDoc}
     */
    public function getReport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReport', []);

        return parent::getReport();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$contact]);

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatBy', []);

        return parent::getCreatBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatBy($creatBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatBy', [$creatBy]);

        return parent::setCreatBy($creatBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getTheme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTheme', []);

        return parent::getTheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setTheme($theme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTheme', [$theme]);

        return parent::setTheme($theme);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeReturn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeReturn', []);

        return parent::getCodeReturn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeReturn($codeReturn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeReturn', [$codeReturn]);

        return parent::setCodeReturn($codeReturn);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageReturn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageReturn', []);

        return parent::getMessageReturn();
    }

    /**
     * {@inheritDoc}
     */
    public function getMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedia', []);

        return parent::getMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedia($media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedia', [$media]);

        return parent::setMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigine', []);

        return parent::getOrigine();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigine($origine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigine', [$origine]);

        return parent::setOrigine($origine);
    }

    /**
     * {@inheritDoc}
     */
    public function setMessageReturn($messageReturn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessageReturn', [$messageReturn]);

        return parent::setMessageReturn($messageReturn);
    }

}
