<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Officine extends \AppBundle\Entity\Officine implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nridPharmacie', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'officinePharmaciens', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nomPharmacie', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'cip', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'adresse', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'localite', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'segment', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'telephoneFixe', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'pmp', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'telephonePmp', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nridGroupement', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nomGroupement', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nridDepositaire', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nomDepositaire', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'canalContrat', 'deleted'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nridPharmacie', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'officinePharmaciens', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nomPharmacie', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'cip', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'adresse', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'localite', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'segment', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'telephoneFixe', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'pmp', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'telephonePmp', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nridGroupement', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nomGroupement', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nridDepositaire', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'nomDepositaire', '' . "\0" . 'AppBundle\\Entity\\Officine' . "\0" . 'canalContrat', 'deleted'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Officine $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNridPharmacie($nridPharmacie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNridPharmacie', [$nridPharmacie]);

        return parent::setNridPharmacie($nridPharmacie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNridPharmacie()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNridPharmacie();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNridPharmacie', []);

        return parent::getNridPharmacie();
    }

    /**
     * {@inheritDoc}
     */
    public function getOfficinePharmaciens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfficinePharmaciens', []);

        return parent::getOfficinePharmaciens();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfficinePharmaciens($officinePharmaciens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfficinePharmaciens', [$officinePharmaciens]);

        return parent::setOfficinePharmaciens($officinePharmaciens);
    }

    /**
     * {@inheritDoc}
     */
    public function setNridGroupement($nridGroupement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNridGroupement', [$nridGroupement]);

        return parent::setNridGroupement($nridGroupement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNridGroupement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNridGroupement', []);

        return parent::getNridGroupement();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomGroupement($nomGroupement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomGroupement', [$nomGroupement]);

        return parent::setNomGroupement($nomGroupement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomGroupement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomGroupement', []);

        return parent::getNomGroupement();
    }

    /**
     * {@inheritDoc}
     */
    public function setPmp($pmp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPmp', [$pmp]);

        return parent::setPmp($pmp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPmp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPmp', []);

        return parent::getPmp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephonePmp($telephonePmp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephonePmp', [$telephonePmp]);

        return parent::setTelephonePmp($telephonePmp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephonePmp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephonePmp', []);

        return parent::getTelephonePmp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPharmacie($nomPharmacie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPharmacie', [$nomPharmacie]);

        return parent::setNomPharmacie($nomPharmacie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPharmacie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPharmacie', []);

        return parent::getNomPharmacie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNridDepositaire($nridDepositaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNridDepositaire', [$nridDepositaire]);

        return parent::setNridDepositaire($nridDepositaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNridDepositaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNridDepositaire', []);

        return parent::getNridDepositaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneFixe($telephoneFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneFixe', [$telephoneFixe]);

        return parent::setTelephoneFixe($telephoneFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneFixe', []);

        return parent::getTelephoneFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCip($cip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCip', [$cip]);

        return parent::setCip($cip);
    }

    /**
     * {@inheritDoc}
     */
    public function getCip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCip', []);

        return parent::getCip();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDepositaire($nomDepositaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDepositaire', [$nomDepositaire]);

        return parent::setNomDepositaire($nomDepositaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDepositaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDepositaire', []);

        return parent::getNomDepositaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite($localite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', [$localite]);

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', []);

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSegment($segment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSegment', [$segment]);

        return parent::setSegment($segment);
    }

    /**
     * {@inheritDoc}
     */
    public function getSegment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegment', []);

        return parent::getSegment();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanalContrat($canalContrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanalContrat', [$canalContrat]);

        return parent::setCanalContrat($canalContrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanalContrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanalContrat', []);

        return parent::getCanalContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

}
