<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pharmacien extends \AppBundle\Entity\Pharmacien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = ['nom' => NULL];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->nom);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'nridInterlocuteur', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'pharmacienOfficines', 'nom', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'prenom', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'sexe', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'civilite', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'titulaire', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'dateNaissance', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'telephoneMobile', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'numeroRpps', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'user', 'deleted'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'nridInterlocuteur', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'pharmacienOfficines', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'prenom', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'sexe', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'civilite', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'titulaire', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'dateNaissance', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'telephoneMobile', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'numeroRpps', '' . "\0" . 'AppBundle\\Entity\\Pharmacien' . "\0" . 'user', 'deleted'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pharmacien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->nom);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNridInterlocuteur($nridInterlocuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNridInterlocuteur', [$nridInterlocuteur]);

        return parent::setNridInterlocuteur($nridInterlocuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNridInterlocuteur()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNridInterlocuteur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNridInterlocuteur', []);

        return parent::getNridInterlocuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentPharmacienOfficines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentPharmacienOfficines', []);

        return parent::getCurrentPharmacienOfficines();
    }

    /**
     * {@inheritDoc}
     */
    public function getPharmacienOfficines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacienOfficines', []);

        return parent::getPharmacienOfficines();
    }

    /**
     * {@inheritDoc}
     */
    public function setPharmacienOfficines($pharmacienOfficines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPharmacienOfficines', [$pharmacienOfficines]);

        return parent::setPharmacienOfficines($pharmacienOfficines);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivilite($civilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivilite', [$civilite]);

        return parent::setCivilite($civilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivilite', []);

        return parent::getCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulaire($titulaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulaire', [$titulaire]);

        return parent::setTitulaire($titulaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulaire', []);

        return parent::getTitulaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneMobile($telephoneMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneMobile', [$telephoneMobile]);

        return parent::setTelephoneMobile($telephoneMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneMobile', []);

        return parent::getTelephoneMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroRpps($numeroRpps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroRpps', [$numeroRpps]);

        return parent::setNumeroRpps($numeroRpps);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroRpps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroRpps', []);

        return parent::getNumeroRpps();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

}
